export default function() {
    // application state is generated by reducer functions
    return [
        { title: 'VW Passat', year: 2008 },
        { title: 'Ford Kuga', year: 2016 },
        { title: 'Tesla Model S', year: 2015 },
        { title: 'Renault Megan', year: 2011 }
    ]
}